version: '3.3'
services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./config/machine/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/machine/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/src
      - ./config/machine/start.sh:/start.sh
    environment:
      - APP_NAME=BasicAccountAPI
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:XDqqJ6btWPHd5gf1NbztLw+479HMIueUrKKSEIQSPf8=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/src/storage/apidb.sqlite
      - LOG_CHANNEL=single
      - CACHE_DRIVER=file
    ports:
      - "80:80"
    restart: always

